server:
  port: 9098
  
spring:
 jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.SQLServer2012Dialect
   hibernate:
     ddl-auto: create
     naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
################
#MSSQL DATASOURCE CONFIG
#BANK DB
 h2:
   datasource:
    url: jdbc:sqlserver://localhost;databaseName=bank
    password: tunctan13
    username: ozaytunctan
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
################
#MSSQL DATASOURCE CONFIG
#MARKET DB
 mssql:
   datasource:
    url: jdbc:sqlserver://localhost;databaseName=marketing
    password: tunctan13
    username: ozaytunctan
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
